--blank-lines-after-declarations
--blank-lines-after-procedures
--blank-lines-before-block-comments
--break-before-boolean-operator
--braces-after-if-line
--braces-after-func-def-line
--brace-indent 0
--blank-before-sizeof
--comment-indentation 40
--case-brace-indentation 4
--case-indentation 4
--indent-level 4
--line-length 80
--dont-cuddle-else
--no-space-after-parentheses
--space-after-procedure-calls
--space-after-for
--space-after-if
--space-after-while
--struct-brace-indentation 0
